### ISSUE TITLE
홈(메인) 페이지 제작

### ISSUE THREAD

**Issue by crystalYoo99** [joowhan/hanbob#2]
**Description**
- 메인 페이지 제작

**Todo**
- [] firebase에서 오늘 데이터 불러와서 표시
- [] 오늘 데이터 없으면 크롤링
- [] 식당별 구별 표시

**ETC**
- 기타사항 없음
